### ISSUE TITLE
Grafana not displaying data (continued)

### ISSUE THREAD

**Issue by abrocksi** [pbrissaud/suivi-bourse#27]
Hi Paul,

I will not reopen issue #7, but have quite the same issue after running docker-compose with portainer. I have attached two screenshots that may help to find the reason for not displaying data. 

![screen01](https://user-images.githubusercontent.com/94559500/161737476-082e2dd4-0450-4846-bf4f-8143c511938f.PNG)
![screen02](https://user-images.githubusercontent.com/94559500/161737501-cdaec3fe-cf33-4925-85e2-b7bc71c6750c.PNG)

It seems to me that prometheus does not receive data, but I am not deep enough in your image/model.

From your [article ](https://medium.com/analytics-vidhya/watch-your-stock-shares-with-grafana-and-influxdb-4df7a99c6d64) I do miss InfluxDB, but I guess you switched meanwhile to prometheus instead.

So, how can I display data in Grafana? Do you need my docker-compose-file? Or any logs?

Thanks for your help in advance

regards Alex

**Comment by abrocksi** [comment]
**In addition**: In Grafana I do see the prometheus stack, but the connection will be refused. So Grafana works, but receives no data.

![screen03](https://user-images.githubusercontent.com/94559500/161739851-73c4374f-af33-41ed-85f7-84b09e76812f.PNG)

**Comment by abrocksi** [comment]
**And again: Good job, Paul!** 
Image 3.1.0 works perfect. In addition, I had to change localhost to my internal IP address and then prometheus was picked up by grafana.
![stocks_screenshots_02](https://user-images.githubusercontent.com/94559500/161819086-aef4c65a-e538-429e-b196-7b6628cfd956.PNG)
![stocks_screenshots_03](https://user-images.githubusercontent.com/94559500/161819121-4c2bf146-4d31-4da7-989f-14bc07bee7ab.PNG)
regards
Alex

**Comment by pbrissaud** [comment]
Perfect !
