### ISSUE TITLE
ModuleNotFoundError: No module named 'prometheus_client'

### ISSUE THREAD

**Issue by abrocksi** [pbrissaud/suivi-bourse#28]
**Describe the bug**
In the protocoll of the "suivi-bourse-app"-Container I receive the message "ModuleNotFoundError: No module named 'prometheus_client'" after strating successfully the docker-compose.yaml.

**To Reproduce**
1. Execute docker-compose.yaml
2. Go to protocoll of "suivi-bourse-app"-Container

**Expected behavior**
No error message because, 'prometheus_client' should be part of the container 

**Screenshots**
![screen05](https://user-images.githubusercontent.com/94559500/161775431-7b399545-a50a-4808-9561-10ffd1767cd7.PNG)
![screen04](https://user-images.githubusercontent.com/94559500/161775405-e6e95b47-8fe6-4d21-a283-a8396295b8a9.PNG)

**Installation mode:** (choose one)
- [ ] Standalone
- [ ] Docker 
- [X] Docker-Compose

regards
Alex

**Comment by pbrissaud** [comment]
Hi,

The new version of the image (3.1.0) fixes this issue ! I tested it and it should work now.

Thanks to contribute to this project

**Comment by abrocksi** [comment]
Perfect Paul! Image 3.1.0 works. "suivi-bourse-app"-Container pulls data and prometheus collects :-)
![stocks_screenshots_01](https://user-images.githubusercontent.com/94559500/161813020-351c8c94-0555-432a-a5b5-f169f0b43713.PNG)
Thanks for the hint!

regards
Alex
