### ISSUE TITLE
Support for InfluxDB V1

### ISSUE THREAD

**Issue by Cavekeeper** [pbrissaud/suivi-bourse#39]
I have a working database with InfluxDB V1. Unfortunately, transferring the collected data from the app has not yet worked. It works fine with Prometheus. Is there also a solution to transfer this to InfluxDB V1?
I use the following docker compose

`version: "3.8"

services:
  app:
    container_name: suivi-bourse-app
    restart: unless-stopped
    environment:
      - SB_SCRAPING_INTERVAL=120
      - INFLUXDB_HOST=http://192.168.x.x
      - INFLUXDB_PORT=8086
      - INFLUXDB_DATABASE=stocks
      - INFLUXDB_USER=user_stocks
      - INFLUXDB_PASSWORD=secretpw
    image: paulbrissaud/suivi-bourse-app:3.1.0
    volumes:
      - /volume1/docker/suivi-bourse-app/config/config.yaml:/home/appuser/.config/SuiviBourse/config.yaml:ro`

**Comment by pbrissaud** [comment]
Hi,

In my opinion, the easiest way to ingest the data into your Influx v1 database is to use the **Telegraf prometheus input**. You can check the documentation here :  https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/README.md

I will maybe add a sample configuration into the documentation.
